"use client"
import localFont from "next/font/local";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css"
import {appStore} from "../store/appStore"
import { Provider } from "react-redux";
import dotEnv from "dotenv"
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  dotEnv.config()
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider store ={appStore}>

        {children}
        </Provider>
      </body>
    </html>
  );
}
